@baseURL = http://localhost:3000

# @name create_user
POST {{baseURL}}/user
Content-Type: application/json

{
    "name": "Lucas",
    "email": "lucas.magaldi@hotmail.com",
    "type": "lojista",
    "cpf": "09882755976"
}